version: '3.0'

services: 
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.3
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin:/root/.pgadmin
    expose:
      - ${PGADMIN_LISTEN_PORT}
    depends_on:
      - postgres

  redis:
    container_name: ${REDIS_HOST}
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}

  backend:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/backend/Dockerfile
    depends_on:
      - postgres
      - redis
    expose:
      - ${BACKEND_UWSGI_PORT}

  nginx:
    image: nginx:1.21-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
      - "${PGADMIN_EXTERNAL_PORT}:${PGADMIN_LISTEN_PORT}"

volumes:
  pgdata:
  pgadmin:
